// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kdukcovdmvuijjvprgzp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkdWtjb3ZkbXZ1aWpqdnByZ3pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MjgxNDUsImV4cCI6MjA2MDUwNDE0NX0.939p0Z3IsP7pRVcIcRNBdzXYqH3oKLGuVbioFn4F9S8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);